[api]
enabled = true

## GENERATOR

[sources.random]
type = "demo_logs"
format = "json"
interval = 2

[sinks.file]
type = "file"
inputs = ["random"]
path = "/tmp/logs/vector-%Y-%m-%d.log"

[sinks.file.encoding]
codec = "json"
timestamp_format = "rfc3339"

## CONFIGURATION

[sources.agent]
type = "datadog_agent"
address = "0.0.0.0:8080"
store_api_key = false

[sinks.datadog]
type = "datadog_logs"
inputs = ["agent"]
default_api_key = "${DD_API_KEY}"

[sinks.datadog.healthcheck]
enabled = true
