version: '2'

services:

  agent:
    image: gcr.io/datadoghq/agent:7
    privileged: true
    volumes:
      - ./logs:/tmp/logs:ro
      - ./agent:/etc/datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
    networks:
      - local

  vector:
    image: timberio/vector:latest-distroless-libc
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./logs:/tmp/logs
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - VECTOR_CONFIG=/etc/vector/vector.toml
      # if you need vector to be verbose
      # - LOG=debug
    networks:
      - local

networks:
  local: {}
